
services:
  prod-db:
    image: postgres
    restart: always
    container_name: prod-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5434:5432
    networks:
      - prod

  prod-back: 
    depends_on:
      - prod-db
    build:
      context: ./back
      dockerfile: Dockerfile
    restart: always
    container_name: prod-back
    environment:
      SPRING_PROFILES_ACTIVE: local,docker
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8080:8090
    networks:
      - prod

  serv-db:
    image: postgres
    restart: always
    container_name: serv-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5534:5532
    networks:
      - prod

  serv-back:
    depends_on:
      - serv-db
    build:
      context: ./back
      dockerfile: Dockerfile
    restart: always
    container_name: serv-back
    environment:
      SPRING_PROFILES_ACTIVE: prod,docker
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8090:8090
    networks:
      - prod

  # Remove this comment once there is a first version of the frontend
  # prod-front:
  #   build:
  #     context: ./front
  #     dockerfile: Dockerfile
  #   container_name: prod-front
  #   ports:
  #     - 4200:80
  #   networks:
  #     - prod

volumes:
  data:

networks:
  prod:
    driver: bridge
