services:
  dev-db:
    image: postgres:17
    restart: always
    container_name: dev-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    ports:
      - 5434:5432
    networks:
      - dev

  dev-back: 
    depends_on:
      - dev-db
    build:
      context: ./back
      dockerfile: Dockerfile
    restart: always
    container_name: dev-back
    env_file:
      - ./back/.env
    environment:
      SPRING_PROFILES_ACTIVE: local,docker
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: dev-db
    ports:
      - 8080:8080
    networks:
      - dev

  serv-db:
    image: postgres:17
    restart: always
    container_name: serv-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - serv-db-data:/var/lib/postgresql/data
    ports:
      - 5534:5432
    networks:
      - prod

  serv-back:
    depends_on:
      - serv-db
    build:
      context: ./back
      dockerfile: Dockerfile
    restart: always
    container_name: serv-back
    env_file:
      - ./back/.env
    environment:
      SPRING_PROFILES_ACTIVE: local,docker
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: serv-db
    ports:
      - 8090:8090
    networks:
      - prod

  # Remove this comment once there is a first version of the frontend
  # dev-front:
  #   build:
  #     context: ./front
  #     dockerfile: Dockerfile
  #   container_name: dev-front
  #   ports:
  #     - 4200:80
  #   networks:
  #     - dev
volumes:
  dev-db-data:
  serv-db-data:

networks:
  prod:
    driver: bridge
  dev:
    driver: bridge
