spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${DB_HOST:serv-db}:${DB_PORT:5432}/postgres

server:
  port: 8090
