spring:
  datasource:
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5534/postgres
  jpa:
    show-sql: 'true'

# Logs
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  servlet:
    context-path: /SoftwareSecProjectA3_25_26_back
  port: 8080

cors:
  allowed-origin: "*"
  insecure: false
  postman-testing: false


jwt:
  secret: ykLx2aidrEhX6Jx58Je/Jg8/F7l/Jx2/RBosVlhgcVV6cZgIYHvLIzRTl4vI0SUs
  refresh-secret: x0OStMBKJVX+Fk3yvL9HIqNIpAoqyIYpbvAjRuQTw5xlJbMtSsDmy4xI63xsiB3f
  token-duration: 1800               # default: 30 min
  refresh-token-duration: 2592000      # default: 1 month
  issuer: SoftwareSecProjectA3_25_26_back

aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    bucket: ${S3_BUCKET_NAME}